# Generated by Django 5.2.7 on 2025-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_image_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
