# Generated by Django 5.2.7 on 2025-10-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_expiry_date_notice_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice_board',
        ),
    ]
