# Generated by Django 5.2.7 on 2025-10-18 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_notice_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachments/'),
        ),
    ]
